name: livre
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0 # For making HTTP requests to the API
  sqflite: ^2.4.2 # For SQLite database operations
  path: ^1.9.1 # For resolving paths to the database file

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
